name: Main CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Run install
        run: |
          pnpm install --frozen-lockfile
      - name: Run build
        run: pnpm run build

  type-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Run install
        run: |
          pnpm install --frozen-lockfile
      - name: Run typecheck
        run: pnpm run typecheck

  lint-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Run install
        run: |
          pnpm install --frozen-lockfile
      - name: Run lint
        run: pnpm run lint

  all-status-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - build-test
      - type-test
      - lint-test
    steps:
      - name: All status check
        run: echo "All status checks passed"
