name: Main CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: shiron-dev/actions/setup-node@v1.1.0
      - name: Run install
        run: |
          pnpm install --frozen-lockfile
      - name: Run build
        run: pnpm run build

  build-storybook-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: shiron-dev/actions/setup-node@v1.1.0
      - name: Run install
        run: |
          pnpm install --frozen-lockfile
      - name: Run build:storybook
        run: pnpm run build:storybook

  type-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: shiron-dev/actions/setup-node@v1.1.0
      - name: Run install
        run: |
          pnpm install --frozen-lockfile
      - name: Run typecheck
        run: pnpm run typecheck

  lint-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: shiron-dev/actions/setup-node@v1.1.0
      - name: Run install
        run: |
          pnpm install --frozen-lockfile
      - name: Run lint
        run: pnpm run lint

  fmt-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: shiron-dev/actions/setup-node@v1.1.0
      - name: Run install
        run: |
          pnpm install --frozen-lockfile
      - name: Run fmt
        run: pnpm run fmt

  vitest-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: shiron-dev/actions/setup-node@v1.1.0
      - name: Run install
        run: |
          pnpm install --frozen-lockfile
      - name: Run test
        run: pnpm run test

  all-status-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - build-test
      - build-storybook-test
      - type-test
      - lint-test
      - vitest-test
    steps:
      - name: All status check
        run: echo "All status checks passed"
